services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoFutureCacheInvalidation\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoFutureCacheInvalidationBundle.php}

    InspiredMinds\ContaoFutureCacheInvalidation\EventListener\OnSubmitCallbackListener:
        public: true
